INSERT INTO "race" ("name", "date", "rank") VALUES 
        ('GRAN PREMIO DE LA REPÚBLICA ARGENTINA', '2022-04-03', '{"Aleix Espargaro","Jorge Martin","Alex Rins","Joan Mir","Francesco Bagnaia","Brad Binder","Maverick Viñales","Fabio Quartararo","Marco Bezzecchi","Enea Bastianini","Luca Marini","Takaaki Nakagami","Miguel Oliveira","Jack Miller","Alex Marquez","Raul Fernandez","Remy Gardner","Darryn Binder","Stefan Bradl","Andrea Dovizioso","Fabio Di Giannantonio","Pol Espargaro","Franco Morbidelli","Johann Zarco"}') 
      ,
        ('GRANDE PRÉMIO DE PORTUGAL', '2022-04-24', '{"Fabio Quartararo","Johann Zarco","Aleix Espargaro","Alex Rins","Miguel Oliveira","Marc Marquez","Alex Marquez","Francesco Bagnaia","Pol Espargaro","Maverick Viñales","Andrea Dovizioso","Luca Marini","Franco Morbidelli","Remy Gardner","Marco Bezzecchi","Takaaki Nakagami","Darryn Binder","Lorenzo Savadori","Fabio Di Giannantonio","Jack Miller","Joan Mir","Brad Binder","Enea Bastianini","Jorge Martin"}') 
      ,
        ('GRAN PREMIO D''ITALIA', '2022-05-29', '{"Francesco Bagnaia","Fabio Quartararo","Aleix Espargaro","Johann Zarco","Marco Bezzecchi","Luca Marini","Brad Binder","Takaaki Nakagami","Miguel Oliveira","Marc Marquez","Fabio Di Giannantonio","Maverick Viñales","Jorge Martin","Alex Marquez","Jack Miller","Darryn Binder","Franco Morbidelli","Michele Pirro","Remy Gardner","Andrea Dovizioso","Raul Fernandez","Lorenzo Savadori","Enea Bastianini","Joan Mir","Alex Rins","Pol Espargaro"}') 
      ,
        ('MOTORRAD GRAND PRIX DEUTSCHLAND', '2022-06-19', '{"Fabio Quartararo","Johann Zarco","Jack Miller","Aleix Espargaro","Luca Marini","Jorge Martin","Brad Binder","Fabio Di Giannantonio","Miguel Oliveira","Enea Bastianini","Marco Bezzecchi","Raul Fernandez","Franco Morbidelli","Andrea Dovizioso","Remy Gardner","Stefan Bradl","Pol Espargaro","Maverick Viñales","Alex Marquez","Takaaki Nakagami","Darryn Binder","Joan Mir","Francesco Bagnaia"}') 
      ,
        ('GRAND PRIX OF THE AMERICAS', '2022-04-10', '{"Enea Bastianini","Alex Rins","Jack Miller","Joan Mir","Francesco Bagnaia","Marc Marquez","Fabio Quartararo","Jorge Martin","Johann Zarco","Maverick Viñales","Aleix Espargaro","Brad Binder","Pol Espargaro","Takaaki Nakagami","Andrea Dovizioso","Franco Morbidelli","Luca Marini","Miguel Oliveira","Raul Fernandez","Remy Gardner","Fabio Di Giannantonio","Darryn Binder","Alex Marquez","Marco Bezzecchi"}') 
      ,
        ('GRAND PRIX DE FRANCE', '2022-05-15', '{"Enea Bastianini","Jack Miller","Aleix Espargaro","Fabio Quartararo","Johann Zarco","Marc Marquez","Takaaki Nakagami","Brad Binder","Luca Marini","Maverick Viñales","Pol Espargaro","Marco Bezzecchi","Fabio Di Giannantonio","Alex Marquez","Franco Morbidelli","Andrea Dovizioso","Darryn Binder","Miguel Oliveira","Francesco Bagnaia","Jorge Martin","Joan Mir","Raul Fernandez","Alex Rins","Remy Gardner"}') 
      ,
        ('TT ASSEN', '2022-06-26', '{"Francesco Bagnaia","Marco Bezzecchi","Maverick Viñales","Aleix Espargaro","Brad Binder","Jack Miller","Jorge Martin","Joan Mir","Miguel Oliveira","Alex Rins","Enea Bastianini","Takaaki Nakagami","Johann Zarco","Fabio Di Giannantonio","Alex Marquez","Andrea Dovizioso","Luca Marini","Stefan Bradl","Remy Gardner","Lorenzo Savadori","Raul Fernandez","Fabio Quartararo","Franco Morbidelli","Darryn Binder"}') 
      ,
        ('GRAND PRIX OF QATAR', '2022-03-06', '{"Enea Bastianini","Brad Binder","Pol Espargaro","Aleix Espargaro","Marc Marquez","Joan Mir","Alex Rins","Johann Zarco","Fabio Quartararo","Takaaki Nakagami","Franco Morbidelli","Maverick Viñales","Luca Marini","Andrea Dovizioso","Remy Gardner","Darryn Binder","Fabio Di Giannantonio","Raul Fernandez","Francesco Bagnaia","Jorge Martin","Miguel Oliveira","Alex Marquez","Jack Miller","Marco Bezzecchi"}') 
      ,
        ('GRAND PRIX OF INDONESIA', '2022-03-20', '{"Miguel Oliveira","Fabio Quartararo","Johann Zarco","Jack Miller","Alex Rins","Joan Mir","Franco Morbidelli","Brad Binder","Aleix Espargaro","Darryn Binder","Enea Bastianini","Pol Espargaro","Alex Marquez","Luca Marini","Francesco Bagnaia","Maverick Viñales","Raul Fernandez","Fabio Di Giannantonio","Takaaki Nakagami","Marco Bezzecchi","Remy Gardner","Jorge Martin","Andrea Dovizioso"}') 
      ,
        ('BRITISH GRAND PRIX', '2022-08-07', '{"Francesco Bagnaia","Maverick Viñales","Jack Miller","Enea Bastianini","Jorge Martin","Miguel Oliveira","Alex Rins","Fabio Quartararo","Aleix Espargaro","Marco Bezzecchi","Brad Binder","Luca Marini","Takaaki Nakagami","Pol Espargaro","Franco Morbidelli","Andrea Dovizioso","Alex Marquez","Remy Gardner","Stefan Bradl","Darryn Binder","Raul Fernandez","Fabio Di Giannantonio","Joan Mir","Johann Zarco"}') 
      ,
        ('GRAN PREMIO DE ESPAÑA', '2022-05-01', '{"Francesco Bagnaia","Fabio Quartararo","Aleix Espargaro","Marc Marquez","Jack Miller","Joan Mir","Takaaki Nakagami","Enea Bastianini","Marco Bezzecchi","Brad Binder","Pol Espargaro","Miguel Oliveira","Alex Marquez","Maverick Viñales","Franco Morbidelli","Luca Marini","Andrea Dovizioso","Fabio Di Giannantonio","Alex Rins","Remy Gardner","Lorenzo Savadori","Jorge Martin","Stefan Bradl","Johann Zarco","Darryn Binder"}') 
      ,
        ('GRAN PREMIO DI SAN MARINO E DELLA RIVIERA DI RIMINI', '2022-09-04', '{"Francesco Bagnaia","Enea Bastianini","Maverick Viñales","Luca Marini","Fabio Quartararo","Aleix Espargaro","Alex Rins","Brad Binder","Jorge Martin","Alex Marquez","Miguel Oliveira","Andrea Dovizioso","Raul Fernandez","Stefan Bradl","Takaaki Nakagami","Darryn Binder","Marco Bezzecchi","Jack Miller","Remy Gardner","Fabio Di Giannantonio","Kazuki Watanabe","Franco Morbidelli","Pol Espargaro","Johann Zarco","Michele Pirro"}') 
      ,
        ('GRAN PREMI DE CATALUNYA', '2022-06-05', '{"Fabio Quartararo","Jorge Martin","Johann Zarco","Joan Mir","Aleix Espargaro","Luca Marini","Maverick Viñales","Brad Binder","Miguel Oliveira","Alex Marquez","Remy Gardner","Darryn Binder","Franco Morbidelli","Jack Miller","Raul Fernandez","Michele Pirro","Pol Espargaro","Andrea Dovizioso","Fabio Di Giannantonio","Enea Bastianini","Marco Bezzecchi","Francesco Bagnaia","Stefan Bradl","Takaaki Nakagami","Alex Rins"}') 
      ,
        ('GRAND PRIX OF JAPAN', '2022-09-25', '{"Jack Miller","Brad Binder","Jorge Martin","Marc Marquez","Miguel Oliveira","Luca Marini","Maverick Viñales","Fabio Quartararo","Enea Bastianini","Marco Bezzecchi","Johann Zarco","Pol Espargaro","Alex Marquez","Franco Morbidelli","Cal Crutchlow","Aleix Espargaro","Fabio Di Giannantonio","Raul Fernandez","Remy Gardner","Takaaki Nakagami","Francesco Bagnaia","Darryn Binder","Alex Rins","Takuya Tsuda","Tetsuta Nagashima"}') 
      ,
        ('GRAN PREMIO DE ARAGÓN', '2022-09-18', '{"Enea Bastianini","Francesco Bagnaia","Aleix Espargaro","Brad Binder","Jack Miller","Jorge Martin","Luca Marini","Johann Zarco","Alex Rins","Marco Bezzecchi","Miguel Oliveira","Alex Marquez","Maverick Viñales","Cal Crutchlow","Pol Espargaro","Remy Gardner","Franco Morbidelli","Darryn Binder","Fabio Di Giannantonio","Raul Fernandez","Marc Marquez","Takaaki Nakagami","Fabio Quartararo"}') 
      ,
        ('MOTORRAD GRAND PRIX VON ÖSTERREICH', '2022-08-21', '{"Francesco Bagnaia","Fabio Quartararo","Jack Miller","Luca Marini","Johann Zarco","Aleix Espargaro","Brad Binder","Alex Rins","Marco Bezzecchi","Jorge Martin","Fabio Di Giannantonio","Miguel Oliveira","Maverick Viñales","Alex Marquez","Andrea Dovizioso","Pol Espargaro","Stefan Bradl","Raul Fernandez","Lorenzo Savadori","Remy Gardner","Franco Morbidelli","Darryn Binder","Takaaki Nakagami","Enea Bastianini","Joan Mir"}') 
      ;